//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVentaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Folio { get; set; }
        public int Cantidad { get; set; }
        public int Producto { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
